### ISSUE TITLE
Add more options for stopping hover-play

### ISSUE THREAD

**Issue by simonlindholm** [simonlindholm/toggle-gifs#17]
https://addons.mozilla.org/en-US/firefox/addon/toggle-animated-gifs/reviews/630440/ suggests stopping on unhover and on click outside, both of which are nice ideas.

Stopping on "click outside" could feasibly be combined with stopping on hovering another GIF, but I can't see how to do options UI for it, so let's ignore that combination. Keyboard shortcuts and "toggle on click" almost replaces it.

**Comment by LL25255252** [comment]
@simonlindholm , Can you please upload again http://simonsoftware.se/temp/toggle-gifs-hover-play-options.xpi . This time with a different version numbering b/c I'm "tired" of seeing Firefox AOM give me 1.2.1.1-signed in the "available Updates" page.
Thanks in advance.

**Comment by simonlindholm** [comment]
Sure, done. Can't sign it, unfortunately. (I really need to get back to this...)

**Comment by LL25255252** [comment]
Thanks for the quick update ("for the record" and for search engines this version is 1.2.2).
