### ISSUE TITLE
Have indicator to distinguish the gif and other normal pictuIres

### ISSUE THREAD

**Issue by ooker777** [simonlindholm/toggle-gifs#24]
I think this will be useful. Maybe a play button, or `this is a gif`, or just `gif`. What do you think?

**Comment by simonlindholm** [comment]
The request has come up in the past and it would be certainly useful, but it turns out be hard to implement, especially when you don't want to affect page load performance. Closing as dup of #16, see the discussion there.

**Comment by LL25255252** [comment]
@ooker777 , this is not a perfect solution but you can try my userstyle:
https://userstyles.org/styles/112111/global-add-dashed-border-to-gif-images

**Comment by ooker777** [comment]
@LL25255252 is your userscript a fork of this addon? What is the relationship between two?

**Comment by LL25255252** [comment]
No it's not a fork. It's not a userscript, it's a userstyle for the Stylish addon based on @simonlindholm idea - see also https://github.com/simonlindholm/toggle-gifs/issues/10#issuecomment-43506260
The style indicates (by adding a dashed border)  which images in the page are animated. Useful especially if the addon's "Pause Gif's by default" is enabled and you can't tell if the image is a regular image or a gif.
Try it. You can always easily uninstall it.

**Comment by Benguin** [comment]
As an alternative that's probably easier, I'd accept the option of having an icon on the toolbar that shows the number of paused gifs.

**Comment by simonlindholm** [comment]
That sounds just as hard to implement (except UI-wise, maybe). The reason for the difficulty is that the addon doesn't get notified about the fact that there exists animated gifs.

**Comment by Benguin** [comment]
Ah, dang. You can't run a script once the page is finished loading to perform a count? How do extensions like videodownloadhelper do things?

**Comment by simonlindholm** [comment]
I *can*, and will have to if I want to add this feature in some form, it just makes me sad to have to slow down page loading for every page ever, just to do that... There's additional complications, too, about images appearing dynamically (not that uncommon), and perhaps the APIs not working before images are displayed for the first time, but I haven't really looked into that.

(Pretty sure Video Downloadhelper does that, possibly with a whitelist. But I haven't looked, so I don't know details.)

**Comment by simonlindholm** [comment]
I managed to figure out how to do this. See #16, and the link in the last comment to an XPI. (Feedback appreciated. I'll make an AMO release soon, even if review queues may prolong that somewhat.)
