### ISSUE TITLE
Could you add a new function for saving the traffic data usage?

### ISSUE THREAD

**Issue by daviking222** [simonlindholm/toggle-gifs#35]
For saving the traffic data usage, add a function that make http request to GIF images intercepted and replaced with a version containing only the first frame of the image sequence.
This is good solution for saving traffic data without break the page layout.\
Could you add this in the future version?
In Chrome there is a extension name "Gif Jam (Animation Stopper)" did this well!! Maybe you can try that extension. Firefox is more powerful but just lack the extension like that!!

**Comment by simonlindholm** [comment]
Dup of #21. It's a hard problem, and I worry that intercepting all network requests could have the effect of making performance worse for general browsing. (I also don't have a lot of time right now to look into it.)

Thanks for the tip about Gif Jam, being able to test how the feature would work in Chromium, and possibly reuse code from https://github.com/adamfur/GifJam is definitely useful.
