### ISSUE TITLE
"Pause GIFs by default" does not work.

### ISSUE THREAD

**Issue by mmehnert** [simonlindholm/toggle-gifs#38]
I checked the check box for "Pause GIFs by default". When I enter a page with animated gifs, they all start playing. Toggling by clicking them works fine.
Firefox version: 45

**Comment by simonlindholm** [comment]
On which page does this happen? (all?) Can you double check that `image.animation_mode` is correctly set to `none` in about:config?

**Comment by mmehnert** [comment]
What I experienced were actually embedded videos that I mistook for gifs.
media.autoplay.enabled;false to the rescue.

**Comment by simonlindholm** [comment]
Great!
