### ISSUE TITLE
Some AJAX loaded images not paused by default?

### ISSUE THREAD

**Issue by verbatim** [simonlindholm/toggle-gifs#40]
On some news sites where pages continually load new content, only the primarily loaded images are paused by default. When new content loads, the images play by default, but do have the start/stop buttons attached and must manually stop those images.

Is this something I must tweak in the preferences? If so, what configuration?

**Comment by simonlindholm** [comment]
That's odd, the pages are supposed to be flagged by the addon never to play animations... Can you give an example of a page where it happens?

**Comment by verbatim** [comment]
I made some setting adjustments and the plugin performs as it's supposed to. I accidentally had a particular site on an exceptions list so that the gifs played rather than stopped by default.

**Comment by simonlindholm** [comment]
Ah, great!
