### ISSUE TITLE
No issue, just a massive <heart> !!!

### ISSUE THREAD

**Issue by DerellLicht** [simonlindholm/toggle-gifs#47]
I'm still using legacy Firefox (56.0.2), because I *hate* the new chromefox junk.  So your legacy version is working *fine* for me, and I just want to deliver a massive HUZZAH !!!  The combination of options that you provide, are EXACTLY the combination of choices that I wanted... this is Perfect !!! 

Thank you very Much !!!!
Derell Licht
Fremont, CA

**Comment by simonlindholm** [comment]
:heart:
